version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "canary"
    groups:
      android-gradle-plugin:
        patterns:
          - "com.android.library"
          - "com.android.application"
          - "com.android.tools.build:gradle"
      detekt:
        patterns:
          - "io.gitlab.arturbosch.detekt"
          - "io.gitlab.arturbosch.detekt:detekt-formatting"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.android"
          - "org.jetbrains.kotlin:kotlin-gradle-plugin"
          - "org.jetbrains.kotlin:kotlin-bom"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "canary"