name: Build APK

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      RELEASE_KEY:
        required: true
      RELEASE_KEY_PASSWORD:
        required: true
      RELEASE_KEY_STORE_PASSWORD:
        required: true
      RELEASE_KEY_ALIAS:
        required: true

jobs:
  build:
    runs-on: macos-14
    env:
      ANDROID_KEYSTORE_FILE: '${{ github.workspace }}/release-key.jks'
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: true
      CCACHE_MAXSIZE: 1G
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: 'recursive'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Retrieve version
        run: |
          git fetch
          if [ ${{ github.ref_type == 'tag' || startsWith(github.ref_name, 'release') }} == true ]; then
            export version=$(git describe --tags --abbrev=0 | sed 's/v//')
          else
            export version=$(echo $(git rev-parse --short=7 HEAD))
          fi
          echo VERSION=$version >> $GITHUB_ENV
          echo VERSION=$version

          export code=$(git rev-list --count HEAD refs/remotes/origin/canary)
          echo CODE=$code >> $GITHUB_ENV
          echo CODE=$code

          echo BRANCH=$(git branch --show-current) >> $GITHUB_ENV
      - name: Prepare for building
        id: prepare
        run: |
          chmod +x gradlew
          base64 --decode <<< "${{ secrets.RELEASE_KEY }}" > "${{ env.ANDROID_KEYSTORE_FILE }}"
          grep -q '[^[:space:]]' "${{ env.ANDROID_KEYSTORE_FILE }}" && echo release_key_exists=true >> $GITHUB_ENV || echo release_key_exists=false >> $GITHUB_ENV
      - name: Cache dict.txt
        uses: actions/cache@v4
        env:
          BRANCH: ${{ env.BRANCH }}
        with:
          path: |
            app/dict.txt
          key: ${{ runner.os }}-dict.txt-${{ env.BRANCH }}
      - name: Setup Gradle & Build APK
        uses: gradle/gradle-build-action@v3
        with:
          gradle-home-cache-cleanup: true
          cache-overwrite-existing: true
          cache-read-only: false
          arguments: assembleRelease
        env:
          VERSION: ${{ env.VERSION }}
          CODE: ${{ env.CODE }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_KEY_STORE_PASSWORD: ${{ secrets.RELEASE_KEY_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          release_key_exists: ${{ env.release_key_exists }}
      - name: Upload built apk
        env:
          release_key_exists: ${{ env.release_key_exists }}
        if: success() && env.release_key_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: |
            app/build/outputs/apk/release/*.apk
      - name: Upload signature
        env:
          release_key_exists: ${{ env.release_key_exists }}
        if: success() && env.release_key_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: signature_v4
          path: |
            app/build/outputs/apk/release/*.idsig
      - name: Upload mappings
        env:
          release_key_exists: ${{ env.release_key_exists }}
        if: success() && env.release_key_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: mappings
          path: app/build/outputs/mapping/release/
      - name: Setup Debug Session
        if: success() != true
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
      
