name: Android CI

on:
  push:
    branches-ignore:
      - website

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      RELEASE_KEY: ${{ secrets.RELEASE_KEY }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      RELEASE_KEY_STORE_PASSWORD: ${{ secrets.RELEASE_KEY_STORE_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}

  build:
    uses: ./.github/workflows/build.yml
    secrets:
      RELEASE_KEY: ${{ secrets.RELEASE_KEY }}
      RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      RELEASE_KEY_STORE_PASSWORD: ${{ secrets.RELEASE_KEY_STORE_PASSWORD }}
      RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
