name: Android CI

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: true
      CCACHE_MAXSIZE: 1G
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: Retrieve version
        run: |
          if [ ${{ github.ref_type}} == "tag" ]; then
            echo VERSION=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//g')
            echo VERSION=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\/v//g') >> $GITHUB_ENV
          else
            echo VERSION=$(echo ${{ github.event.head_commit.id }} | head -c 7)
            echo VERSION=$(echo ${{ github.event.head_commit.id }} | head -c 7) >> $GITHUB_ENV
          fi
      - name: Build with Gradle
        env: 
          VERSION: ${{ env.VERSION }}
          RELEASE_KEY: ${{ secrets.RELEASE_KEY }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_KEY_STORE_PASSWORD: ${{ secrets.RELEASE_KEY_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        run: |
          bash .ci/build.sh
      - name: Upload built apk
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: snapshot
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/apk/release/*.json
      
